---
platform: linux

inputs:
- name: terraform-infra
- name: bosh-state
- name: bosh-deployment

run:
  path: bash
  args:
  - -euc
  - |
    export BBL_GCP_SERVICE_ACCOUNT_KEY=$(jq -r '.service_account_key' terraform-infra/metadata | base64 --decode)
    pushd bosh-state/bbl-state
      bbl plan \
        --lb-type cf \
        --iaas gcp \
        --lb-cert $(jq -r '.bbl_cert' terraform-infra/metadata) \
        --lb-key $(jq -r '.bbl_private_key' terraform-infra/metadata) \
        --lb-domain "${DOMAIN}"
    popd
    sleep 60
