---
platform: linux

params:
  DOMAIN:
  BBL_GCP_REGION:

inputs:
- name: terraform-infra
- name: bosh-state

outputs:
- name: bosh-state

run:
  path: bash
  args:
  - -euc
  - |
    function tar-bbl-state() {
      status=$?
      cd ${root_dir}/bosh-state
      tar czf state.tgz bbl-state
      exit $status
    }

    root_dir=${PWD}

    trap tar-bbl-state EXIT

    export BBL_GCP_SERVICE_ACCOUNT_KEY=$(jq -r '.service_account_key' terraform-infra/metadata | base64 --decode)
    jq -r '.bbl_cert' terraform-infra/metadata > cert.pem
    jq -r '.bbl_private_key' terraform-infra/metadata > key

    pushd bosh-state/bbl-state
      bbl plan \
        --lb-type cf \
        --iaas gcp \
        --lb-cert ../../cert.pem \
        --lb-key ../../key \
        --lb-domain "${DOMAIN}"
      bbl up
    popd
