---
platform: linux

params:
  GCP_CREDENTIALS_JSON:
  PROJECT_ID:

run:
  path: bash
  args:
  - -euc
  - |
    echo "${GCP_CREDENTIALS_JSON}" > googlecreds.json
    export gcreds=$PWD/googlecreds.json
    gcloud auth activate-service-account --key-file="$gcreds"

    mkdir -p bbl-state
    tar czf state.tgz bbl-state
    touch cf-vars.yml

    set +e
    gsutil ls gs://${PROJECT_ID}/bosh/state.tgz
    resp_bosh=$?
    gsutil ls gs://${PROJECT_ID}/cf/cf-vars.yml
    resp_cf=$?
    set -e
    if [[ $resp_bosh -gt 0 ]]; then
      gsutil cp state.tgz gs://${PROJECT_ID}/bosh/state.tgz
    fi
    if [[ $resp_cf -gt 0 ]]; then
      gsutil cp cf-vars.yml gs://${PROJECT_ID}/cf/cf-vars.yml
    fi
